### ISSUE TITLE
taskNotificationTapCallback not called on Android 12

### ISSUE THREAD

**Issue by letisoft** [781flyingdutchman/background_downloader#92]
taskNotificationTapCallback is never called when I tap on the notification. Works on Android 11 not on Android 12

    FileDownloader().configureNotification(
        running: TaskNotification('Downloading', 'file: {filename}'),
        complete: TaskNotification('Download finished', 'file: {filename}'),
        progressBar: true
    );

    FileDownloader().registerCallbacks(
        taskNotificationTapCallback:(Task task, NotificationType notificationType){
          print("getting call");
        }
    );

but callback never called when I tap on the notification, no errors in the logs

**Comment by 781flyingdutchman** [comment]
Can you try to add to your application's manifest:
```
<queries>
    <package android:name="com.android.chrome" />
</queries>
```
(and replace the chrome package reference with there reference to your own app)?

It may have something to do with [this](https://stackoverflow.com/questions/30446052/getlaunchintentforpackage-is-null-for-some-apps#65140578) .

**Comment by edgarMejia** [comment]
Same here, I just add:

```xml
<queries>
    <package android:name="com.android.chrome" />
</queries>
```

The "taskNotificationTapCallback" event is still not called.
It doesn't work on iOS either :(

**Comment by 781flyingdutchman** [comment]
Hi, I tested the sample app on Android API 31 (Android 12) and for me it works as expected. Can you try with the example app?

**Comment by 781flyingdutchman** [comment]
I've tried to improve the 'retry logic' for the notificationTap message that comes from Android to Flutter. I can't tell if it makes difference, but please do give it a try. Change your pubspec.yaml to:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: tap_notification
```

Also, just to be precise, and because it's suspicious that the example app works but your app doesn't: your app's  AndroidManifest.xml should include, under `<activity`:
```
android:exported="true"
android:launchMode="singleTask"
```

See the manifest for the example app.

**Comment by 781flyingdutchman** [comment]
I've created a branch with additional logging to see if we can better understand what is going on. Please change your pubspec.yaml reference as follows:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: tap_notification
```

Then run _your_ app, download a file, wait for that to complete, then tap the notification. Please share the Flutter output (not the logcat, because I have printed a few things in FlutterDownloader using debugPrint).  In particular, keep the lines that contain 'taptap'.

For reference, for the example app on my machine in the emulator that looks like this:

```
I/flutter (18797): taptap have set background channel listener
I/BackgroundDownloader(18797): Enqueuing task with id 2586780492
I/TaskWorker(18797): Starting task with taskId 2586780492
V/BackgroundDownloader(18797): taptap set tapIntent PendingIntent{9ebcbea: android.os.BinderProxy@2834edb}
V/BackgroundDownloader(18797): taptap set tapIntent PendingIntent{1832731: android.os.BinderProxy@baece16}
V/BackgroundDownloader(18797): taptap set tapIntent PendingIntent{c73d984: android.os.BinderProxy@9b2056d}
V/BackgroundDownloader(18797): taptap set tapIntent PendingIntent{dc1b5a2: android.os.BinderProxy@e1de233}
V/BackgroundDownloader(18797): taptap set tapIntent PendingIntent{41709f0: android.os.BinderProxy@2768b69}
I/TaskWorker(18797): Successfully downloaded taskId 2586780492 to /data/user/0/com.bbflight.background_downloader_example/app_flutter/my/directory/zipfile.zip
V/BackgroundDownloader(18797): taptap set tapIntent PendingIntent{72989ee: android.os.BinderProxy@ca6e8f}
I/WM-WorkerWrapper(18797): Worker result SUCCESS for Work [ id=ed4a91a3-9cae-4c19-aa75-f6f26da3c6e3, tags={ com.bbflight.background_downloader.TaskWorker, BackgroundDownloader, taskId=2586780492, group=default } ]
V/BackgroundDownloader(18797): taptap handleIntent
V/BackgroundDownloader(18797): taptap handleIntent send background message 0
I/flutter (18797): taptap received notificationTap message
I/flutter (18797): Tapped notification NotificationType.complete for taskId 2586780492
V/BackgroundDownloader(18797): taptap handleIntent background message true
```

You can see the creation of the tapIntent that is attached to the notifications (several, one for each progress update) and the handleIntent message which is where the app is processing the intent: it sends a background message to the Flutter app, where it is received and processed, and the downloader receives 'true' back to confirm the background message was delivered.

Let's see what your logs tell us!

**Comment by pavkoccino** [comment]
Hey, thank you so much for dealing with this.

Here is the log file.
[background_downloader_log.txt](https://github.com/781flyingdutchman/background_downloader/files/12180962/background_downloader_log.txt)

I must say on the first sight, the result seems very similar to what you posted, but the code inside the TapCallBack body is just not executed.

I decided to also attach project's AndroidManifest.xml (xml is not supported, so uploading as txt) as there are no secrets there.
[AndroidManifest.txt](https://github.com/781flyingdutchman/background_downloader/files/12181071/AndroidManifest.txt)
Note that after every change of the manifest I follow the rule where I run flutter clean first.

I was suspicious of following part, but even after removing of this and trying without it, still does not work. I am on physical device, Android 13.

```dart
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
```

**Comment by 781flyingdutchman** [comment]
OK, good news is that the message is making it from native code back to Flutter. The issue seems to be that it cannot find a registered callback to call when it gets there. I've added a few more log messages to the latest commit on this branch to debug that, so can you please run it again?  Can you also let me know _where_ you register your callback, as I am concerned with the activity starts/stops we may be 'losing' that registered callback somewhere. Thanks!

**Comment by pavkoccino** [comment]
Sorry, cannot use the latest commit as it won't compile, you forgot some ending quotes and dash.

```dart
/C:/Users/.../AppData/Local/Pub/Cache/git/background_downloader-1e8cbd66c73e215df580b529db108f021504d130/lib/src/base_downloader.dart:486:18: Error: String starting with ' must end with '.
        log.fine('taptap no callback found);
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/.../AppData/Local/Pub/Cache/git/background_downloader-1e8cbd66c73e215df580b529db108f021504d130/lib/src/base_downloader.dart:486:17: Error: Can't find ')' to match '('.
        log.fine('taptap no callback found);
                ^
/C:/Users/.../AppData/Local/Pub/Cache/git/background_downloader-1e8cbd66c73e215df580b529db108f021504d130/lib/src/base_downloader.dart:487:9: Error: Expected ',' before this.
        await Future.delayed(
        ^^^^^
``` 

I can still answer where I register the callback tho.

So I have a class called FilesDownloader in which I've implemented static wrapper methods around your FileDownloader() functions. Basically I have 2 methods, one for singleDownload and one for batch. No matter which one is called first I check if initialization has been done (just bool flag inside FilesDownloader class) and in case it was not, I call the initializeFilesDownloader method which code I posted earlier:

```dart
  static void initializeFilesDownloader() {
    _log.d('Initializing FilesDownloader');
    FileDownloader()
        .registerCallbacks(taskNotificationTapCallback: myNotificationTapCallback) // TODO does not work
        .configureNotification(
          running: TaskNotification(LocaleKeys.downloading.tr(), 'file: {filename}'),
          complete: TaskNotification(LocaleKeys.downloadingFinished.tr(), 'file: {filename}'),
          progressBar: true,
        );
    hasBeenInitialized = true;
  }
```

**Comment by 781flyingdutchman** [comment]
Ugh, that's what I get from editing and committing directly in GitHub - sorry! Should be fixed now, so please try again as I'd like to see the logs.

There are a few possible issues here:
1. The FileDownloader lost track of the callback you registered -> seems unlikely, but the new logs will show that
2. The callback you registered no longer exists -> if that callback is associated with an object (i.e. is not a top level function) then is it possible that due to an app resume/restart you recreate that object (and leave the former callback invalid)? One way to test is to register a simple top-level function as your callback and print something (like the example app does). If that works, then this is likely the issue and you'll have to debug or rethink your architecture, as the callback needs to stay valid.  One simple workaround may be to register the tapCallback immediately after you create the object that has the callback method - there is no cost to registering a callback, it will simply replace the previously registered one.

**Comment by 781flyingdutchman** [comment]
Thinking a bit more about this, this issue may also extend to your initialization of the FileDownloader itself.  You do that in a static function, and I am not entirely sure how Dart handles a singleton (which is what FileDownloader is) in that context. Does it keep it around, or does it garbage-collect it when there is no _object_ that is using it?  If it is garbage-collected it will show in the logs as having no memory of the registered callbacks by the time it needs it (issue 1 above).  You could try doing your initialization in the `initState` of a top level widget (or even before you call `runApp`) instead of in a static method and see if that makes a difference

**Comment by pavkoccino** [comment]
Okay, so here is another log. Personally I don't see any difference. Seems like it is not getting into `processNotificationTap` function where you log the callbacks.

[background_downloader_log_28072023.txt](https://github.com/781flyingdutchman/background_downloader/files/12193905/background_downloader_log_28072023.txt)

I get what you are saying with potentially losing the registeredCallback because of the GC, but wouldn't that also mean that `_notificationConfigs` would get also lost? And they don't...

I did something extra and I tried to instantiate your FileDownloader later after the initialization and debug the object and the object has the callback registered as you can see on following screen. So to wrap it up, it seems it is not getting lost.
![Uploading instantiating_file_downloader_later.png…]()

**Comment by 781flyingdutchman** [comment]
Thanks and this is getting really weird, because the first line of my `processNotificationTap` function is to log that it is called. Are you sure you updated the pull from the repo (you have to call `flutter pub upgrade` not just `flutter pub get`)?  I just added another debugPrint so please pull again.

Either way, since we are now clearly getting the message on the Flutter side, you can also debug regularly. Set a breakpoint at `native_downloader.dart` line 89 (at the debugPrint statement that does appear in your logs, so must be called) and step through from there. It should be clear where it is trying to find your callback - it is simply looking it up in the map you show above, keyed by the task's `group` (and that is where there could be an issue too, so please let me know what you find)

**Comment by 781flyingdutchman** [comment]
Actually, I think I know what the problem is. I pushed another commit that should fix it, I think (please `pub get upgrade`).

Here's what's happening (if you are interested):
* You are using what I call a 'convenience' function (e.g. `FileDownloader().download`) where you `await` the result, instead of the raw function `enqueue`. 
* Per [this](https://github.com/781flyingdutchman/background_downloader#grouping-tasks), when you do that, the downloader changes the task's `group` field from `FileDownloader.defaultGroup` to `FileDownloader.awaitGroup`, so that it can intercept the status callbacks and handle those for you, so you only get to see the result.  Normally you don't notice this (and I even do some back and forth to make `resume` work for those - this was an earlier bug), but here you do, because you configured your notification for the default group, by omitting the `group` parameter in your `registerCallbacks` call. That means you configured a callback for `default`, but the notification task's group has been modified to `await`, so it sees no callback for that group when you tap it
* Reasonably expected behavior is that the default callback should work for `await` group tasks, so I have modified the registration call to _also_ set the `notificationTapCallback` for `await` if you set it for `default`

Sorry I didn't think of this before: the reference to a specific platform made me think the issue was on the native side.

I think this fixes the issue if you indeed are using `download`. If you are using `enqueue` then I don't know why this happens, and we need to continue with the debugging per above.

**Comment by edgarMejia** [comment]
I have been following your thread, in my case the latest changes you uploaded have been working for me on iOS and Android.

I am using GetX to have the logic separated from the view.

**webview_controller.dart:**
```dart
class WebViewController extends GetxController {
  Rx<DownloadTask?> downloadTask = Rx<DownloadTask?>(null);
  RxBool isDownloading = false.obs;

  Future<void> downloadFile(String url, String mime) async {
    if (isDownloading.value) {
      return;
    }

    FileDownloader().configureNotification(
      running: TaskNotification('Descargando', 'archivo: {filename}'),
      complete: TaskNotification('Descarga finalizada', 'archivo: {filename}'),
      progressBar: true,
      tapOpensFile: Platform.isIOS
    ).registerCallbacks(
        taskNotificationTapCallback:(Task task, NotificationType notificationType){
          print("NotificationTapCallback: Getting call");
        }
    );

    downloadTask.value = await DownloadTask(
      url: url,
      headers: sessionHeaders,
      baseDirectory: Platform.isAndroid
          ? BaseDirectory.temporary
          : BaseDirectory.applicationDocuments,
      updates: Updates.statusAndProgress,
      retries: 5,
      allowPause: true,
    ).withSuggestedFilename(unique: true);

    isDownloading(true);
    
    // Download logic ...
}
```

**Logs from Android 13 simulator:**
```
V/BackgroundDownloader( 8948): taptap handleIntent
V/BackgroundDownloader( 8948): taptap handleIntent send background message 0
I/flutter ( 8948): taptap received notificationTap message
I/flutter ( 8948): taptap task.group=await and callbacks are: {default: Closure: (Task, NotificationType) => void, await: Closure: (Task, NotificationType) => void}
I/flutter ( 8948): calling your callback Closure: (Task, NotificationType) => void
I/flutter ( 8948): NotificationTapCallback: Getting call
V/BackgroundDownloader( 8948): taptap handleIntent background message true
```

**Comment by pavkoccino** [comment]
Wohooo, thank you so much for fixing it. Can you let me know when you publish new version?

Happy ending log:
```dart
I/flutter (19811): taptap received notificationTap message
I/flutter (19811): taptap task.group=await and callbacks are: {default: Closure: (Task, NotificationType) => void from Function 'myNotificationTapCallback': static., await: Closure: (Task, NotificationType) => void from Function 'myNotificationTapCallback': static.}
I/flutter (19811): calling your callback Closure: (Task, NotificationType) => void from Function 'myNotificationTapCallback': static.
I/flutter (19811): Tapped notification NotificationType.complete for taskId 2909588368
```

**Comment by 781flyingdutchman** [comment]
Awesome! Glad we got this finally figured out!  Just published in version V7.8.1.  Thanks much for your help debugging this one!

**Comment by rusfearuth** [comment]
Using 7.9.1 version. I still have the problem of not calling **taskNotificationTapCallback** for iOS.

**Comment by 781flyingdutchman** [comment]
Is the exact same code working when you run it on Android? Have you made the required [changes](https://pub.dev/packages/background_downloader#setup-for-notifications)  to the app delegate?
